version: "3"
networks:
  mediaserver:
services:
  sonarr:
    networks:
      - mediaserver
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./config/sonarr:/config
      - ./media:/media #optional
      - ./downloads:/downloads #optional
    ports:
      - 8989:8989
    # restart: unless-stopped
  qbittorrent:
    networks:
      - mediaserver
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - WEBUI_PORT=8080
    volumes:
      - ./config/qbittorrent:/config
      - ./downloads:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    # restart: unless-stopped
  jellyfin:
    networks:
      - mediaserver
    image: lscr.io/linuxserver/jellyfin:latest
    # image: lscr.io/linuxserver/jellyfin:nightly
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - JELLYFIN_PublishedServerUrl=192.168.0.5 #optional
    volumes:
      - ./config/jellyfin:/config
      - ./media/shows:/data/tvshows
      - ./media/movies:/data/movies
      - ./media/anime:/data/anime
      - ./media/books:/data/books
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    # restart: unless-stopped
  jackett:
    networks:
      - mediaserver
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - AUTO_UPDATE=true #optional
      - RUN_OPTS=<run options here> #optional
    volumes:
      - ./config/jackett:/config
      - ./downloads:/downloads
    ports:
      - 9117:9117
    # restart: unless-stopped
  jellyseerr:
    networks:
      - mediaserver
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
        - LOG_LEVEL=debug
        - TZ=Europe/Amsterdamn
    ports:
        - 5055:5055
    volumes:
        - ./config/jellyseerr:/app/config
    # restart: unless-stopped
  radarr:
    networks:
      - mediaserver
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - ./config/radarr:/config
      - ./media/movies:/movies #optional
      - ./downloads:/downloads #optional
    ports:
      - 7878:7878
    # restart: unless-stopped
  homarr:
    networks:
      - mediaserver
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    # restart: unless-stopped
    volumes:
      - ./config/homarr:/app/data/configs
      - ./homarr-icons:/app/public/icons
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - '7575:7575'
  bazarr:
    networks:
      - mediaserver
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./config/bazarr:/config
      - ./media/:/media
    ports:
      - 6767:6767
    # restart: unless-stopped
  readarr:
    networks:
      - mediaserver
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./config/readdar:/config
      - ./media/books:/books #optional
      - ./downloads:/downloads #optional
    ports:
      - 8787:8787
    # restart: unless-stopped